#!/bin/sh
workspaces() {

desktops=$(bspc query -D --names | awk 'BEGIN{ ORS=" " }{ print }')
ws=()
for desktop in $desktops; do
  ws+=($desktop)
done

# Unoccupied
un="0"

# check if Occupied
o1=$(bspc query -D -d .occupied --names | grep "${ws[0]}" )
o2=$(bspc query -D -d .occupied --names | grep "${ws[1]}" )
o3=$(bspc query -D -d .occupied --names | grep "${ws[2]}" )
o4=$(bspc query -D -d .occupied --names | grep "${ws[3]}" )
o5=$(bspc query -D -d .occupied --names | grep "${ws[4]}" )
o6=$(bspc query -D -d .occupied --names | grep "${ws[5]}" )

# check if Focused
f1=$(bspc query -D -d .active --names | grep "${ws[0]}" )
f2=$(bspc query -D -d .active --names | grep "${ws[1]}" )
f3=$(bspc query -D -d .active --names | grep "${ws[2]}" )
f4=$(bspc query -D -d .active --names | grep "${ws[3]}" )
f5=$(bspc query -D -d .active --names | grep "${ws[4]}" )
f6=$(bspc query -D -d .active --names | grep "${ws[5]}" )

ic_1="祿"
ic_2="祿"
ic_3="祿"
ic_4="祿"
ic_5="祿"
ic_6="祿"

if [ $o1 ]; then
    ic_1=""
fi
if [ $o2 ]; then
    ic_2=""
fi
if [ $o3 ]; then
    ic_3=""
fi
if [ $o4 ]; then
    ic_4=""
fi
if [ $o5 ]; then
    ic_5=""
fi
if [ $o6 ]; then
    ic_6=""
fi

if [ $f1 ]; then
    ic_1="綠"
elif [ $f2 ]; then
    ic_2="綠"
elif [ $f3 ]; then
    ic_3="綠"
elif [ $f4 ]; then
    ic_4="綠"
elif [ $f5 ]; then
    ic_5="綠"
elif [ $f6 ]; then
    ic_6="綠"
fi

echo 	"(box	:class \"works\"	:orientation \"h\" :spacing 15 :space-evenly \"false\" (button :onclick \"bspc desktop -f ${ws[0]}\"	:class	\"$un$o1$f1\"	\"$ic_1\") (button :onclick \"bspc desktop -f ${ws[1]}\"	:class \"$un$o2$f2\"	 \"$ic_2\") (button :onclick \"bspc desktop -f ${ws[2]}\"	:class \"$un$o3$f3\" \"$ic_3\") (button :onclick \"bspc desktop -f ${ws[3]}\"	:class \"$un$o4$f4\"	\"$ic_4\") (button :onclick \"bspc desktop -f ${ws[4]}\"	:class \"$un$o5$f5\" \"$ic_5\")  (button :onclick \"bspc desktop -f ${ws[5]}\"	:class \"$un$o6$f6\" \"$ic_6\"))"

}
workspaces
bspc subscribe desktop node_transfer | while read -r _ ; do
workspaces
done
